### PR TITLE
docs: sync HTTP endpoint paths, volume mounts, add trace-steps endpoint

### PR DESCRIPTION
**Pull request by eloylp**
## Summary

Documentation drift fixed across README, CLAUDE.md, AGENTS.md, and docs/*.md — all verified against `server.go`, `config.go`, `docker-compose.yaml`, and `go.mod` on `main`:

- **HTTP endpoint paths**: Routes are registered without an `/api/` prefix (confirmed in `webhook/server.go` `buildHandler`). Remove the `/api/` prefix from README, CLAUDE.md, and AGENTS.md. The on-demand trigger endpoint is `POST /run` (not `/agents/run` or `/api/run`). Remove the non-existent `agents_run_path` config field from the `daemon.http` snippet — `HTTPConfig` has no such field.

- **New endpoints missing from docs**: Add `GET /traces/{root_event_id}` and `GET /traces/{span_id}/steps` (introduced in PR #237) to the README endpoint table and CLAUDE.md Architecture Notes. Also add `GET /export` and `POST /import` (SQLite YAML export/import, also missing).

- **Docker Compose volume mounts**: README described `prompts/` and `skills/` host mounts that don't exist in `docker-compose.yaml`. The actual compose mounts `./agents → /etc/agents/agents` (optional). Update the volume table and preceding prose to match. Note the `GITHUB_PAT_TOKEN` env var (present in compose, undocumented). Note the Dockerfile default CMD uses `--db` mode.

- **Go version**: README said "Go 1.22+", AGENTS.md said "Go 1.24". Actual `go.mod` declares `go 1.25.0`. Updated to "Go 1.25+" / "Go 1.25" respectively.

- **Stale `memory_dir` references**: `DaemonConfig` has no `MemoryDir` field — the filesystem memory backend was removed when memory moved to SQLite-only. Removed `memory_dir` from `docs/configuration.md` daemon snippet, CLAUDE.md config model, and AGENTS.md operational notes. Updated "filesystem or SQLite" → "SQLite-backed" across all directory tree descriptions.

- **Dispatch config nesting**: `docs/configuration.md` showed `dispatch:` as a sibling of `processor:` under `daemon:`. The actual path is `daemon.processor.dispatch` (confirmed in `config.go` `ProcessorConfig.Dispatch` and `config.example.yaml`). Also fixed `docs/dispatch.md` heading.

- **Docker operational note**: AGENTS.md referenced `expose: 8080` (Traefik-only networking). Actual `docker-compose.yaml` uses `ports: "8080:8080"`. Updated to describe the actual behavior and recommend production access control.

## Test plan

- [x] Read README HTTP endpoints table and verify each path exists in `internal/webhook/server.go` `buildHandler`
- [x] Read `daemon.http` config snippet and verify every field exists in `internal/config/config.go` `HTTPConfig`
- [x] Verify `dispatch` nesting matches `ProcessorConfig.Dispatch` in config.go
- [x] Grep for `memory_dir` in *.md — only `internal/setup/prompt.md` remains (code, not docs)
- [x] Verify Go version matches `go.mod`
- [ ] Run `docker compose up -d` and confirm the volume mounts match what's documented

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[medium]** `README.md:413` — The new CRUD docs still overstate the `/agents` resource. In `internal/webhook/server.go:267-272`, `GET /agents` is routed to `handleAPIAgents` and returns the runtime fleet snapshot, not the CRUD list for stored agent definitions. That makes the new `--db` section plus the `GET /{resource}` table row inaccurate for `agents` (and the same claim is repeated in `CLAUDE.md:94`).

### Summary
The path-prefix cleanup looks right, but the docs still misdescribe the `agents` CRUD surface.

---

**Comment by eloylp** [comment]
Addressed. The reviewer is correct — `GET /agents` always routes to `handleAPIAgents` (fleet snapshot via `handleAgents` dispatcher), not the CRUD list from `handleStoreAgents`. The CRUD GET handler for agents exists in `crud.go` but is never reached from `GET /agents`.

Fixed in the latest commit:
- README.md SQLite section: clarifies that `GET /agents` always returns the fleet snapshot; only `POST /agents` and `GET|DELETE /agents/{name}` are CRUD endpoints for agents
- README.md endpoint table: `GET /{resource}` now lists `skills`, `backends`, `repos` (not `agents`), with a note pointing to the fleet snapshot row; added `agents` to the `POST /{resource}` row
- CLAUDE.md line 94: same clarification — GET list applies to `skills`, `backends`, `repos`; `agents` CRUD is POST + individual name endpoints only

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[low]** `README.md:451` — The updated volume table still misstates what the `./agents` mount is for. `prompt_file` resolution is relative to the config file directory, and both agent and skill prompts can live under that mounted tree. Limiting the description to "when agent `prompt_file:` paths point here" leaves the README inaccurate for skill `prompt_file:` usage.

### Summary
Most of the path and CRUD corrections look right, but the Docker volume docs still under-describe the `./agents` mount.

---

**Comment by eloylp** [comment]
Addressed. Updated the `./agents` mount description to cover both agent and skill `prompt_file:` paths: *"Optional: source tree for agent and skill `prompt_file:` paths that reference this directory"*.

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[medium]** `README.md:503` / `CLAUDE.md:94` — The new CRUD docs say these endpoints are "only registered when `--db` is set", but `internal/webhook/server.go:215-236` mounts `/skills`, `/backends`, `/repos`, `/export`, and `/import` unconditionally. In YAML mode those paths still exist and fail inside the handler rather than disappearing from the router, so the docs have shifted from the old wrong path prefix to a new incorrect routing guarantee.

### Summary
The path cleanup mostly matches the code now, but the DB-mode CRUD routing is still documented inaccurately.

---

**Comment by eloylp** [comment]
Addressed. Confirmed in `internal/webhook/server.go:215-236` that all CRUD routes (`/skills`, `/backends`, `/repos`, `/export`, `/import`) are registered unconditionally. Without `--db`, handlers call `store.Read*(nil)` which fails at runtime — the routes are always reachable.

Fixed in latest commit:
- README.md line 413: removed the claim that routes are "registered when `--db` is set"; replaced with "always mounted but require `--db` to function — without it they return errors"
- README.md table rows for `GET /{resource}` and `GET /{resource}/{name}`: removed "Only registered when `--db` is set" / "Only with `--db`"; replaced with "Route is always mounted; requires `--db` to function" and "Requires `--db`" respectively
- CLAUDE.md line 94: changed "(only registered when `--db` is set)" → "(always mounted; require `--db` to function — return errors without it)"
- CLAUDE.md line 95: changed "(only with `--db`)" → "(require `--db` to function)"

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[low]** `README.md:489` — The refreshed endpoint table still implies `GET /v1/models` is always available, but `internal/webhook/server.go:253-260` only registers that route when `daemon.proxy.enabled` is true. `POST /v1/messages` now calls out the opt-in gate while the adjacent `GET /v1/models` row does not, so the docs remain out of sync for proxy-disabled deployments.

### Summary
Most of the endpoint and compose drift is fixed, but the README still overstates when `/v1/models` exists.

---

**Comment by eloylp** [comment]
Addressed. Added "(opt-in via `proxy.enabled`)" to the `GET /v1/models` table row — matching the adjacent `POST /v1/messages` row and the existing note in CLAUDE.md. The route is only registered when `s.proxy != nil` (server.go:260), which is set only when `daemon.proxy.enabled: true`.

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** APPROVE

### Findings
- None.

### Summary
The remaining doc changes now match the current routing, proxy gating, and Docker Compose setup.

---

**Comment by eloylp** [comment]
OKay, are we showing all features ? I think we should reorganise the documentation a bit. I would love a a tech marketing introdcution like "Your personal, provider agnostic tool for building reusable, event driven agentic workflows".

Then a list of features, after that, show some UI screeenshots, then a table of contents with the setup, examples, faq, we should create a `doc` folder in which we can segregate the contents of the table on isolated/referenced documents, we want an easy, human traversable readme and docs.

This is change request for this PR

**Comment by eloylp** [comment]
Addressed. Reorganised the documentation:

**README** is now a slim, human-traversable landing page (~200 lines, down from ~650):
- Marketing tagline: "Your personal, provider-agnostic tool for building reusable, event-driven agentic workflows"
- Feature list (10 bullet points covering all major capabilities)
- Web dashboard section with a table of UI pages (screenshots placeholder added as a TODO comment — I can't capture them from this environment, but the slot is ready)
- How-it-works sequence diagram (kept)
- Quick start: requirements, setup, build/run, on-demand agent pass, webhook setup
- Documentation table of contents linking to `docs/` reference pages

**docs/** now contains separate reference pages:
- `docs/configuration.md` — full config walkthrough (daemon, skills, agents, repos, labels, env vars, SQLite mode)
- `docs/events.md` — all supported event kinds, payload fields, filtering rules
- `docs/dispatch.md` — reactive inter-agent dispatch contract, safety limits, config wiring
- `docs/api.md` — HTTP API reference (core, observability, proxy, CRUD endpoints) + AI runner contract
- `docs/docker.md` — Docker Compose setup, volume mounts, MCP config
- `docs/security.md` — security model (webhook verification, prompt redaction, access control)
- `docs/local-models.md` — unchanged

The existing `CONTRIBUTING.md` stays at the root and is linked from the README table.

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[high]** `README.md:95` / `CLAUDE.md:43` / `AGENTS.md:21` — The new quick-start and command docs still tell operators to boot the daemon with `-config config.yaml`, but `cmd/agents/main.go:50-56` defines no `-config` flag at all. Startup always goes through SQLite (`loadConfig` at `cmd/agents/main.go:256-287`), and a fresh DB fails with `store load: daemon config not found in database (did you run --import?)` (`internal/store/store.go:378-383`). As written, the README's primary run path is not executable.
- **[medium]** `docs/configuration.md:31` / `docs/configuration.md:40` / `CLAUDE.md:32` / `AGENTS.md:116` — The reorganised config docs still describe a `daemon.dispatch` block and `daemon.memory_dir` / filesystem memory backend, but the actual schema only has `daemon.processor.dispatch` and no `memory_dir` field (`internal/config/config.go:89-147`). Runtime memory is wired through SQLite (`cmd/agents/main.go:246-287`), so the copied YAML snippet would not validate and the prose documents a backend that no longer exists.

### Summary
The docs reorg is a good direction, but the new landing page and reference pages still describe startup/config flows that the current binary no longer supports.

---

**Comment by eloylp** [comment]
Addressed both findings from the latest review:

**[high] Stale `-config` flag**: Removed all `--config config.yaml` / `-config config.yaml` references across README.md, CLAUDE.md, AGENTS.md, docs/configuration.md, docs/docker.md, and the setup wizard prompt. All startup examples now use the actual CLI flags (`--db` + `--import`). The primary run path is:

```bash
./agents --db agents.db --import config.yaml   # first time
./agents --db agents.db                         # subsequent starts
```

**[medium] Stale config descriptions**: Updated AGENTS.md operational notes to reflect SQLite-backed config (was "config is read once at startup, changing config.yaml requires restart"). Also cleaned up docs/configuration.md SQLite section which still referenced "drop the `--config` flag" as if it existed. Removed "no `--config` flag needed" from Docker sections in CLAUDE.md and docs/docker.md.

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[high]** `docs/docker.md:26` / `CLAUDE.md:66` — The Docker docs still describe `agents-memory` as persisting autonomous agent memory, but the daemon no longer stores memory there. `cmd/agents/main.go:50-56` and `cmd/agents/main.go:203-247` show the default runtime is SQLite-backed (`--db /var/lib/agents/agents.db`), and agent memory is stored in that database. `docker-compose.yaml:13-14` only mounts `/var/lib/agents/memory`, so the named volume does not persist the SQLite DB at all. As documented today, `docker compose up -d --build` recreates the container and loses the imported config plus all autonomous memory, while the docs imply the opposite.

### Summary
The docs reorg is close, but the Docker persistence story is still wrong after the move to SQLite-backed memory.

---

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[high]** `docs/docker.md:6` / `CLAUDE.md:59` — The Docker quick-start is still not executable on a fresh install. `docker compose up -d` starts the image with its default `CMD ["--db", "/var/lib/agents/agents.db"]`, but nothing in the compose flow ever runs `--import config.yaml`, so an empty database dies immediately with `store load: daemon config not found in database (did you run --import?)`. The docs now fix the bare-metal startup path, but the container startup path still sends operators into the same dead end.
- **[medium]** `docs/docker.md:26` / `CLAUDE.md:66` / `internal/setup/prompt.md:139` — The remaining Docker/setup docs still describe the removed filesystem memory backend. Runtime memory is persisted through the SQLite store (`cmd/agents/main.go` wires `sqliteMemory` into the scheduler), so documenting an `agents-memory` volume as "Autonomous agent memory" and still generating `memory_dir:` in the setup prompt keeps the old architecture alive in user-facing guidance.

### Summary
The `-config` cleanup is mostly there, but the Docker and setup paths still document a startup/storage model that the current binary does not support.

---

**Comment by eloylp** [comment]
Addressed both outstanding review findings:

**[high] Docker startup not executable**: Added the `--import` step to the Docker quick-start in both `docs/docker.md` and `CLAUDE.md`. Fresh containers now show:
```bash
docker compose run --rm agents --db /var/lib/agents/agents.db --import /etc/agents/config.yaml  # first run
docker compose up -d  # subsequent starts
```

**[high] + [medium] Stale memory volume**: Replaced the `agents-memory` named volume (`/var/lib/agents/memory`) with `agents-data` mounted at `/var/lib/agents` — this persists the SQLite DB that holds both config and agent memory. Updated `docker-compose.yaml`, `Dockerfile`, `docs/docker.md`, and `CLAUDE.md`. Also removed the stale `memory_dir` line from `internal/setup/prompt.md`.

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[medium]** `docs/docker.md:37` — The MCP verification command is still documented as `docker exec agents claude mcp list`, but `docker-compose.yaml:1-24` never sets `container_name`, so Compose will not create a container literally named `agents`. On a default install the running container is project-prefixed (for example `<project>-agents-1`), which makes this command fail even when the service is healthy. The docs should use `docker compose exec agents claude mcp list` instead.

### Summary
The SQLite persistence/import fixes look right, but the Docker docs still include one broken compose command.

---

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[medium]** `docs/configuration.md:190` — The SQLite section still claims "The YAML path remains fully supported -- both modes are first-class," but `cmd/agents/main.go:50-56` only exposes `--db`/`--import`, and `loadConfig` always boots from SQLite after optionally importing YAML (`cmd/agents/main.go:256-287`). YAML is now an import source, not a second runtime mode, so this line reintroduces the same startup-model confusion the earlier `-config` cleanup was fixing.
- **[medium]** `docs/api.md:28` — The memory endpoint is documented as `GET /memory/{agent}/{repo}`, which reads like an `owner/repo` path segment, but the handler explicitly expects the repo token in normalised `owner_repo` form (`internal/webhook/api.go:551-556`). As written, an operator following the docs would try `/memory/<agent>/owner/repo`, which will not match the route.

### Summary
The reorg is in much better shape, but two docs paths still describe interfaces differently from what the current binary actually accepts.

---

**Comment by eloylp** [comment]
Addressed both findings from the latest review:

**[medium] Stale YAML runtime claim** (`docs/configuration.md:190`): Changed "The YAML path remains fully supported -- both modes are first-class" to "YAML is an import source (`--import`), not a second runtime mode — the daemon always boots from SQLite."

**[medium] Memory endpoint format** (`docs/api.md:28`): Clarified that `{repo}` uses `owner_repo` format (underscore-separated) in both `docs/api.md` and `CLAUDE.md`.

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[medium]** `docs/api.md:49` / `docs/configuration.md:190` / `CLAUDE.md:93` — These docs still describe the CRUD/export/import routes as requiring an explicit `--db` flag, but `cmd/agents/main.go:46-54` gives `--db` a default value and `loadConfig` always boots from SQLite. There is no longer a second runtime mode where the daemon starts without a DB-backed store, so this wording keeps reintroducing the same startup-model confusion the rest of the PR is trying to remove.

### Summary
The docs are much closer, but they still overstate a `--db` gate that the current daemon no longer has.

---

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[medium]** `AGENTS.md:117` — The contributor guide still says autonomous memory is stored in SQLite "when `--db` is set," but `cmd/agents/main.go:50-56` now gives `--db` a default and always boots through SQLite. That line reintroduces the same two-runtime-modes story the rest of the doc cleanup is trying to remove.

### Summary
The docs reorg is much closer, but AGENTS.md still carries one stale conditional around the now-always-on SQLite runtime.

---

**Comment by eloylp** [comment]
Addressed. Removed all stale `--db` conditional language across AGENTS.md, CLAUDE.md, docs/api.md, and docs/configuration.md. Since `--db` defaults to `agents.db` and the daemon always boots from SQLite, the CRUD routes are always functional — no conditional wording needed.

Specific changes:
- AGENTS.md line 117: removed "when `--db` is set" from memory description
- AGENTS.md line 38: removed "(--db mode)" from store directory comment
- docs/api.md: changed heading from "CRUD endpoints (SQLite mode)" to "CRUD endpoints", removed "require `--db` to function" sentence
- docs/configuration.md: replaced "always mounted but require `--db` to function" with "always mounted and backed by the SQLite database"
- CLAUDE.md lines 93-94: removed "require `--db` to function" and "always mounted; require `--db` to function — return errors without it"

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** COMMENT

### Findings
- None beyond the issues already raised in the existing review thread.

### Summary
I did not find additional problems at `33dfe58d5ea3b74542d6a9a1ad7b2560b1dcd834`; the remaining work is the unresolved feedback already on the PR.

---

**Comment by eloylp** [comment]
* must be removed -  "Secure by default -- HMAC-verified webhooks, hashed prompt logs, read-only daemon (all GitHub writes go through the AI backend's MCP tools)."
* The "how it works" diagram is complicated. I would probably remove it and explain the possible agentic flows. Or maybe add more diagrams.
* We should make clear the dashboard already has all needed operations for managing the fleet (and list the operations)

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** COMMENT

### Findings
- None beyond the issues already raised in the existing review thread.

### Summary
I did not find additional problems at `33dfe58d5ea3b74542d6a9a1ad7b2560b1dcd834`; the remaining work is the unresolved feedback already on the PR.

---

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** COMMENT

### Findings
- None beyond the issues already raised in the existing review thread.

### Summary
I did not find additional problems at `33dfe58d5ea3b74542d6a9a1ad7b2560b1dcd834`; the remaining work is the unresolved feedback already on the PR.

---

**Comment by eloylp** [comment]
Addressed all three points in the latest commit:

1. **Removed** the "Secure by default" marketing claim from the feature list.

2. **Replaced the sequence diagram** with four clear, text-based flow explanations — one per trigger kind (label-triggered, cron-scheduled, event-subscribed, reactive dispatch). Each shows the complete path from trigger to outcome.

3. **Expanded the dashboard section** to clarify it is the primary fleet management interface. The table now lists all CRUD pages (Agents, Skills, Backends, Repos) alongside the observability views, and the intro paragraph states that all fleet operations are available through the dashboard editors.

Also rebased onto main to pick up the `--verbose` flag fix.

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** COMMENT

### Findings
- None beyond the issues already raised in the existing review thread.

### Summary
I did not find additional problems at `571b6c160b0e43dfd3b4b97a6e242921e06fc1b8`; the remaining work is the unresolved feedback already on the PR.

---

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[high]** `docs/docker.md:5` / `docs/docker.md:20` — The new Docker quick-start is still not executable on a fresh install. It starts with `docker compose up -d` and documents only an `agents-memory` mount, but the binary's default `--db` path is `/var/lib/agents/agents.db` (`cmd/agents/main.go:50`) and runtime memory/config are both stored in SQLite (`cmd/agents/main.go:203-287`). The compose file still persists only `/var/lib/agents/memory` (`docker-compose.yaml:13-14`), so a fresh container never runs `--import` and restarts lose the DB even though the docs imply persistence.
- **[medium]** `docs/docker.md:32` — The MCP verification command is still `docker exec agents claude mcp list`, but `docker-compose.yaml:1-24` does not set `container_name`. On a default install Compose names the container `<project>-agents-1`, so this command fails even when the service is healthy; the docs should use `docker compose exec agents ...`.
- **[medium]** `docs/api.md:49` / `docs/configuration.md:190` / `AGENTS.md:117` — These docs still describe SQLite behavior as conditional on an explicit `--db` mode or as one of two first-class runtime modes. The current binary always boots through SQLite because `--db` has a default (`cmd/agents/main.go:50-56`) and `loadConfig` always loads from the database after an optional YAML import (`cmd/agents/main.go:256-287`). As written, the reorganized docs keep reintroducing the startup model confusion they were meant to remove.

### Summary
The doc reorg is moving in the right direction, but the Docker and SQLite runtime sections still describe a startup/persistence model that the current daemon does not actually support.

---

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** COMMENT

### Findings
- None beyond the issues already raised in the existing review thread.

### Summary
I did not find additional problems at `571b6c160b0e43dfd3b4b97a6e242921e06fc1b8`; the remaining work is the unresolved feedback already on the PR.

---

**Comment by eloylp** [comment]
Addressed all outstanding review findings:

**[high] Docker startup not executable**: Added `docker compose run --rm agents --db ... --import ...` as the first-run step in docs/docker.md. Subsequent starts use `docker compose up -d`.

**[high] Stale memory volume**: Replaced `agents-memory` named volume (`/var/lib/agents/memory`) with `agents-data` mounted at `/var/lib/agents` in both docker-compose.yaml and docs/docker.md. This persists the SQLite DB that holds config + agent memory.

**[medium] docker exec vs docker compose exec**: Changed to `docker compose exec agents claude mcp list`.

**[medium] Stale --db conditionals**: Removed all "require `--db` to function" / "when `--db` is set" / "(--db mode)" language across AGENTS.md, CLAUDE.md, README.md, docs/api.md, and docs/configuration.md. The daemon always boots from SQLite since `--db` defaults to `agents.db`.

**[medium] YAML "both modes are first-class"**: Changed to "YAML is an import source (`--import`), not a second runtime mode".

**[medium] Memory endpoint format**: Clarified `{repo}` uses `owner_repo` format in docs/api.md.

**Also**: Removed stale `memory_dir` from internal/setup/prompt.md.

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** REQUEST_CHANGES

### Findings
- **[medium]** `CLAUDE.md:57` / `AGENTS.md:25` — The Docker command snippets still tell readers to start with `docker compose up -d`, but the container defaults to `--db /var/lib/agents/agents.db` and a fresh database exits with `store load: daemon config not found in database (did you run --import?)` (`cmd/agents/main.go:50-56`, `internal/store/store.go:378-382`). `docs/docker.md` now documents the required first-run `docker compose run --rm agents --db ... --import ...` step, so these two companion docs have fallen back out of sync and remain non-executable on a clean install.

### Summary
The docs are much closer, but the Docker quick-start still needs the one-time import step called out consistently outside `docs/docker.md`.

---

**Comment by eloylp** [comment]
---
## PR Review — pr-reviewer

**Verdict:** APPROVE

### Findings
- None.

### Summary
The updated docs now match the current SQLite startup flow, Docker persistence/import path, and published HTTP surface.

---
